<?php $this->headTitle('Liste des contacts'); ?>

<h2><?= $this->translate('Contact list') ?></h2>

<table class="table table-striped">
    <?php foreach ($contacts as $c) : ?>
    <tr>
        <td><?= $this->escapeHtml($c->getPrenom()) ?> <?= $this->escapeHtml($c->getNom()) ?></td>
        <td>
            <a href="<?= $this->url('address-book-contact/show', ['id' => $this->escapeUrl($c->getId())]) ?>" class="btn btn-xs btn-primary">Afficher</a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>