<?php $this->headTitle('Liste des contacts'); ?>

<h2>Liste des contacts</h2>

<table class="table table-striped">
    <?php foreach ($contacts as $c) : ?>
    <tr>
        <td><?= $c->getPrenom() ?> <?= $c->getNom() ?></td>
        <td>
            <a href="<?= $this->url('address-book-contact/show', ['id' => $c->getId()]) ?>" class="btn btn-xs btn-primary">Afficher</a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>