<?php $this->headTitle('Afficher un contact'); ?>

<h2>Afficher un contact</h2>

<p>Prénom : <?= $this->escapeHtml($contact->getPrenom()) ?></p>

<p>Nom : <?= $this->escapeHtml($contact->getNom()) ?></p>

<?php if ($contact->getEmail()) : ?>
<p>Email : <?= $this->escapeHtml($contact->getEmail()) ?></p>
<?php endif; ?>

<?php if ($contact->getTelephone()) : ?>
<p>Téléphone : <?= $this->escapeHtml($contact->getTelephone()) ?></p>
<?php endif; ?>